# Application Details
spring.application.name=e-commerce-backend-design

server.port=${PORT:8080}

# Database Connection Configuration (No local fallbacks)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-version=1
spring.flyway.baseline-on-migrate=${FLYWAY_BASELINE_ON_MIGRATE:true}


# JWT Security Configurations
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration.ms=86400000

app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS}
