spring.application.name=e-commerce-backend-design

# MySQL Database Connection Settings
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=topik712
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Properties
# 'update' automatically updates your DB schema based on your Java Entity classes
spring.jpa.hibernate.ddl-auto=update

# Shows the generated SQL queries in your terminal console (great for debugging)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.servlet.context-path=/api/v1

#security config
spring.security.user.name= saifulaziz
spring.security.user.password= pass